# Generated by Django 4.2.4 on 2023-08-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название события')),
                ('description', models.TextField(default='описание ....', max_length=50, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('location', models.CharField(max_length=50, verbose_name='Местоположение события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
