# Generated by Django 4.2.4 on 2023-08-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('release_dt', models.DateField(verbose_name='Дата выпуска')),
                ('expiry_dt', models.DateField(verbose_name='Дата окончание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
