# Generated by Django 4.2.4 on 2023-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='expiry_dt',
            new_name='end_dt',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='release_dt',
            new_name='start_dt',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='описание...', max_length=50, verbose_name='Описание'),
        ),
    ]
