# Generated by Django 4.0.10 on 2023-10-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_expiry_dt_project_end_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_dt',
        ),
    ]
